src/Entity/Brand.php
<?php

namespace App\Entity;

use App\Repository\BrandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BrandRepository::class)
 */
class Brand
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="brand", orphanRemoval=true)
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(\DateTimeInterface $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setBrand($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getBrand() === $this) {
                $product->setBrand(null);
            }
        }

        return $this;
    }
}

src/Form/BrandType.php
<?php

namespace App\Form;

use App\Entity\Brand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BrandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Brand::class,
        ]);
    }
}

src/Controller/BrandController.php
<?php

namespace App\Controller;

use App\Entity\Brand;
use App\Form\BrandType;
use App\Repository\BrandRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/brand")
 */
class BrandController extends AbstractController
{
    /**
     * @Route("/", name="brand_index", methods={"GET"})
     */
    public function index(BrandRepository $brandRepository): Response
    {
        return $this->render('brand/index.html.twig', [
            'brands' => $brandRepository->findByDeletedAt(),
        ]);
    }

    /**
     * @Route("/new", name="brand_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $brand = new Brand();
        $form = $this->createForm(BrandType::class, $brand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($brand);
            $entityManager->flush();

            return $this->redirectToRoute('brand_index');
        }

        return $this->render('brand/new.html.twig', [
            'brand' => $brand,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="brand_show", methods={"GET"})
     */
    public function show(Brand $brand): Response
    {
        return $this->render('brand/show.html.twig', [
            'brand' => $brand,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="brand_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Brand $brand): Response
    {
        $form = $this->createForm(BrandType::class, $brand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('brand_index');
        }

        return $this->render('brand/edit.html.twig', [
            'brand' => $brand,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="brand_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Brand $brand): Response
    {
        if ($this->isCsrfTokenValid('delete'.$brand->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $brand->setDeletedAt(new \DateTime());
            $entityManager->persist($brand);
            $entityManager->flush();
        }

        return $this->redirectToRoute('brand_index');
    }
}

templates/brand/_delete_form.html.twig
<form method="post" action="{{ path('brand_delete', {'id': brand.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ brand.id) }}">
    <button class="btn">Delete</button>
</form>

templates/brand/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/brand/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Brand{% endblock %}

{% block body %}
    <h1>Edit Brand</h1>

    {{ include('brand/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('brand_index') }}">back to list</a>

    {{ include('brand/_delete_form.html.twig') }}
{% endblock %}

templates/brand/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Brand index{% endblock %}

{% block body %}
    <h1>Brand index</h1>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th>*</th>
            <th>Nom</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for brand in brands %}
            <tr>
                <td>{{ brand.id }}</td>
                <td>{{ brand.name }}</td>
                <td>
                    <a href="{{ path('brand_show', {'id': brand.id}) }}">
                        <i class="eye icon"></i>
                    </a>
                    <a href="{{ path('brand_edit', {'id': brand.id}) }}">
                        <i class="edit icon"></i>
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('brand_new') }}">Créer</a>

{% endblock %}

templates/brand/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Brand{% endblock %}

{% block body %}
    <h1>Create new Brand</h1>

    {{ include('brand/_form.html.twig') }}

    <a href="{{ path('brand_index') }}">back to list</a>
{% endblock %}

templates/brand/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Brand{% endblock %}

{% block body %}
    <h1>Brand</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ brand.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ brand.name }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ brand.deletedAt ? brand.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('brand_index') }}">back to list</a>

    <a href="{{ path('brand_edit', {'id': brand.id}) }}">edit</a>

    {{ include('brand/_delete_form.html.twig') }}
{% endblock %}